---
title: "Broken Liner (small)"
author: "Ernesto Carrella"
date: "February 16, 2019"
output: html_document
editor_options: 
  chunk_output_type: console
---



```{r setup, include=FALSE}
set.seed(0)
knitr::opts_chunk$set(echo = FALSE, warning= FALSE, message=FALSE,
                      cache=TRUE,cache.extra = knitr::rand_seed,
                      dpi = 300, fig.width = 13.3, fig.height = 10)
library(abctools)
source('./setup.R')
library(tidyverse)
```

```{r dataprep}
library(EasyABC)
RUNS_TO_MAKE<-MEDIUM_DATA_SET_SIZE

#draws at random until xlim then draws a line
broken_liner_model<-function(b,xlim=5){
  x<-1:10
  y<-rnorm(length(x),mean=0,sd=1)
  for(i in 1:length(x))
  {
    if(x[i]>xlim)
      y[i]<-y[i]+x[i]*b
  }
  return(y)
}


run_toy_model<-function(b){
  y<-
    broken_liner_model(b=b)
   return(
    data.frame(
      y1=y[1],
      y2=y[2],
      y3=y[3],
      y4=y[4],
      y5=y[5],
      y6=y[6],
      y7=y[7],
      y8=y[8],
      y9=y[9],
      y10=y[10]
    )
    
  )
}

total_data<-
  data.frame(
    b = runif(RUNS_TO_MAKE,0,+2)

  )
total_data<-pmap_df(total_data,run_toy_model) %>% cbind(total_data)


param_names<-c("b")
x_names<-setdiff(colnames(total_data),param_names)

```

# ABC

## Rejection


```{r rejection}
rejection_cross<-
  cross_validate_abc(total_data,ngroup=5,method="rejection",parameter_colnames = param_names)
print_table(rejection_cross)

```

## Rejection - semiauto


```{r rejection-sabc}
rejection_cross_sabc<-
  cross_validate_abc(total_data,ngroup=5,method="rejection",parameter_colnames = param_names,
                     semiauto = TRUE)
print_table(rejection_cross_sabc)

```

## Rejection - 1D


```{r rejection-sabc1d, eval=FALSE}
rejection_cross_sabc1d<-
  cross_validate_abc(total_data,ngroup=5,method="rejection",parameter_colnames = param_names,
                     semiauto = TRUE,
                     satr=list(function(x){outer(x,Y=1,"^")}))
print_table(rejection_cross_sabc1d)

```

## Loclin


```{r loclin}
loclin_cross<-
  cross_validate_abc(total_data,ngroup=5,method="loclinear",
                     hcorr=TRUE,parameter_colnames = param_names,
                     semiauto = FALSE)
print_table(loclin_cross)

```

## Neural-Network

```{r neuralnet, eval=TRUE, message= FALSE, results="hide"}
neuralnet<-
  cross_validate_abc(total_data,ngroup=5,method="neuralnet",
                     hcorr=TRUE,parameter_colnames = param_names)

```
```{r}
print_table(neuralnet)

```

# Linear regression


## Degree 1

```{r lm}
lm_cross<-
  cross_validate_lm(total_data,ngroup=5,
                    parameter_colnames = param_names,x_names=x_names,
                     degree=1)
print_table(lm_cross)

```

# Random Forest



```{r rf}
rf_cross<-
  cross_validate_rf(total_data,ngroup=5,
                    parameter_colnames = param_names,x_names=x_names)
print_table(rf_cross)

```


# Loess Fit



```{r loess}
loess_cross<- cross_validate_loess(total_data,ngroup=5,
                    parameter_colnames = param_names,
                    x_names=x_names)
print_table(loess_cross)

```

# Random Forest (boot)



```{r rfboot, results="hide"}
rfboot_cross<-
  cross_validate_rfboot(total_data,ngroup=5,
                    parameter_colnames = param_names,x_names=x_names)

```

```{r rfboottable}
print_table(rfboot_cross)
```


# Average



```{r average}
average_cross<- cross_validate_average(total_data,ngroup=5,
                    parameter_colnames = param_names,
                    x_names=x_names)
print_table(average_cross)

```

```{r, writetocsv}
FILENAME<-"brokenliner_medium"

crosses<-
  list(
    rejection = rejection_cross,
    sabc_4d = rejection_cross_sabc,
#    sabc_1d = rejection_cross_sabc1d, does not work
    loclin = loclin_cross,
    neuralnet = neuralnet,
    lm = lm_cross,
    rf = rf_cross,
    loess = loess_cross,
    rfboot = rfboot_cross,
    average = average_cross
  )

write_csv(
  map2_df(crosses,names(crosses),~ as_data_frame(t(.x$error)) %>% 
            mutate(method=.y)) %>% gather(parameter,value,-method), 
  paste("./errors/",FILENAME,".csv",sep="")
)

write_csv(
  map2_df(crosses,names(crosses),~ as_data_frame(t(.x$contained)) %>% 
            mutate(method=.y)) %>% gather(parameter,value,-method),   paste("./contained/",FILENAME,".csv",sep="")
)

write_csv(
  map2_df(crosses,names(crosses),~ as_data_frame(t(.x$interval)) %>% 
            mutate(method=.y)) %>% gather(parameter,value,-method), 
  paste("./intervals/",FILENAME,".csv",sep="")
)
```
