---
title: "Earthworm jim"
author: "Ernesto Carrella"
date: "February 16, 2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning= FALSE, message=FALSE,
                      cache=TRUE,
                      dpi = 300, fig.width = 13.3, fig.height = 10)
library(abctools)
source('./setup.R')
library(tidyverse)
```

Earthworm jim ABM


```{r dataprep}
# I add to add a "row.number" column name to the file to read this correctly
dr_sumstat<-read_delim("~/Downloads/results_simple_1e5.txt",delim=" ",
                     col_names=TRUE) %>%
  dplyr::select(-row.number)


# I add to add a "row.number" column name to the file to read this correctly
dr_parameters<-
  read_delim("~/Downloads/priors_simple_1e5 (1).txt",delim=" ",
             col_names=TRUE) %>%
  dplyr::select(-row.number)


total_data<-
  cbind(dr_parameters,dr_sumstat)

#this is just too big to do a full cross-validation routine. Let's just pick a decent number of test cases and be done with it
test_data<- 
  withSeed({
  total_data %>%
    sample_n(SMALL_DATA_SET_SIZE) 
  },
  seed = SMALL_DATA_RANDOM_SEED
  )
training_data<-
      anti_join(total_data,test_data)


param_names<-colnames(dr_parameters)
param_names<-setdiff(param_names,"M")
x_names<-colnames(dr_sumstat)
```
# ABC

## Rejection


```{r rejection}
rejection_cross<-
  abc_testing(
    training_set = training_data,
    testing_set = test_data,
    parameter_colnames = param_names,
    method="rejection"
  )
print_table(rejection_cross)

```

## Rejection - semiauto


```{r rejection-sabc}
rejection_cross_sabc<-
    abc_testing(
    training_set = training_data,
    testing_set = test_data,
    parameter_colnames = param_names,
    method="rejection",
    semiauto = TRUE
  )
print_table(rejection_cross_sabc)

```

## Rejection - 1D


```{r rejection-sabc1d}
rejection_cross_sabc1d<-
    abc_testing(
    training_set = training_data,
    testing_set = test_data,
    parameter_colnames = param_names,
    method="rejection",
    semiauto = TRUE,
    satr=list(function(x){outer(x,Y=1,"^")}))

print_table(rejection_cross_sabc1d)

```

## Loclin

Loclin fails

```{r loclin, eval=FALSE}
loclin_cross<-
  abc_testing(
    training_set = training_data,
    testing_set = test_data,
    parameter_colnames = param_names,
    method="loclinear",
    hcorr=TRUE
  )
print_table(loclin_cross)

```

## Neural-Network


```{r neuralnet, eval=TRUE, message= FALSE, results="hide"}
neuralnet<-
    abc_testing(
    training_set = training_data,
    testing_set = test_data,
    parameter_colnames = param_names,
    method="neuralnet",
    hcorr=TRUE
  )

```
```{r, eval=TRUE}
print_table(neuralnet)

```

# Linear regression


## Degree 1

```{r lm}
lm_cross<-
  
  
  biglm_regression_fit(
    training_set = training_data,
    testing_set = test_data,
     parameter_colnames = param_names,
    x_names=x_names,
                     degree=1 
  )
print_table(lm_cross)

```


# Random Forest



```{r rf}
rf_cross<-
  randomForest_fit(    training_set = training_data,
    testing_set = test_data,
                    parameter_colnames = param_names,x_names=x_names)
print_table(rf_cross)

```



# Loess Fit


```{r loess}
loess_cross<-
  loess_fit(training_set = training_data,
    testing_set = test_data,
                    parameter_colnames = setdiff(param_names,"M"),
    x_names=x_names,
    bam=TRUE)

print_table(loess_cross)

```

# Random Forest (boot)



```{r rfboot, results="hide",eval=TRUE}

# faster but not caret
rfboot_cross<-
 randomForest_boot_fit(    training_set = training_data,
    testing_set = test_data,
                    parameter_colnames = setdiff(param_names,"M"),x_names=x_names)

```

```{r rfboottable, eval=TRUE}
print_table(rfboot_cross)
```


# Average



```{r average}
average_cross<- average_fit( training_set = training_data,
    testing_set = test_data,
                    parameter_colnames = param_names,x_names=x_names)
print_table(average_cross)

```

```{r, writetocsv, cache=FALSE, eval=TRUE}
FILENAME<-"earthwormjim"

crosses<-
  list(
    rejection = rejection_cross,
    sabc_4d = rejection_cross_sabc,
    sabc_1d = rejection_cross_sabc1d,
 #   loclin = loclin_cross,
    neuralnet = neuralnet,
    lm = lm_cross,
    rf = rf_cross,
    rfboot = rfboot_cross,
    loess = loess_cross,
    average = average_cross
  )

write_csv(
  map2_df(crosses,names(crosses),~ as_data_frame(t(.x$error)) %>% 
            mutate(method=.y)) %>% gather(parameter,value,-method), 
  paste("./errors/",FILENAME,".csv",sep="")
)

write_csv(
  map2_df(crosses,names(crosses),~ as_data_frame(t(.x$contained)) %>% 
            mutate(method=.y)) %>% gather(parameter,value,-method),   paste("./contained/",FILENAME,".csv",sep="")
)

write_csv(
  map2_df(crosses,names(crosses),~ as_data_frame(t(.x$interval)) %>% 
            mutate(method=.y)) %>% gather(parameter,value,-method), 
  paste("./intervals/",FILENAME,".csv",sep="")
)
```
