---
title: "gk distributions"
author: "Ernesto Carrella"
date: "February 16, 2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning= FALSE, message=FALSE,
                      cache=TRUE,
                      dpi = 300, fig.width = 13.3, fig.height = 10)
library(gk) #unexplicably, gk library overrides the abc function in the abc library
library(abctools)
source('./setup.R')
library(tidyverse)
```

```{r dataprep}
NOBS<-1000 #observations for each call in rgk

total_data<-
  data.frame(
    A = runif(MEDIUM_DATA_SET_SIZE,0,10),
    B= runif(MEDIUM_DATA_SET_SIZE,0,10),
    g= runif(MEDIUM_DATA_SET_SIZE,0,10),
    k = runif(MEDIUM_DATA_SET_SIZE,0,10)

  )

# run gk model and returns deciles as summary statistics
run_gk_model<-function(A,B,g,k,nobs=NOBS){
  simulation<-
    rgk(nobs, A=A, B=B, g=g, k=k)
  
  
  
   return(
   
    quantile(simulation,probs = 0:10/10) %>% as.list() %>% as.data.frame()
    
  )
}

total_data<-pmap_df(total_data,run_gk_model) %>% cbind(total_data)
param_names<-c("A","B","g","k")
x_names<- setdiff(colnames(total_data),param_names) 


```

# ABC

## Rejection


```{r rejection}
rejection_cross<-
  cross_validate_abc(total_data,ngroup=5,method="rejection",parameter_colnames = param_names)
print_table(rejection_cross)

```

## Rejection - semiauto


```{r rejection-sabc}
rejection_cross_sabc<-
  cross_validate_abc(total_data,ngroup=5,method="rejection",parameter_colnames = param_names,
                     semiauto = TRUE)
print_table(rejection_cross_sabc)

```

## Rejection - 1D


```{r rejection-sabc1d}
rejection_cross_sabc1d<-
  cross_validate_abc(total_data,ngroup=5,method="rejection",parameter_colnames = param_names,
                     semiauto = TRUE,
                     satr=list(function(x){outer(x,Y=1,"^")}))
print_table(rejection_cross_sabc1d)

```

## Loclin


```{r loclin}
loclin_cross<-
  cross_validate_abc(total_data,ngroup=5,method="loclinear",
                     hcorr=TRUE,parameter_colnames = param_names,
                     semiauto = FALSE)
print_table(loclin_cross)

```


## Neural-Network

```{r neuralnet, eval=TRUE, message= FALSE, results="hide"}
neuralnet<-
  cross_validate_abc(total_data,ngroup=5,method="neuralnet",
                     hcorr=TRUE,parameter_colnames = param_names)

```
```{r}
print_table(neuralnet)

```


# Linear regression


## Degree 1

```{r lm}
lm_cross<-
  cross_validate_lm(total_data,ngroup=5,
                    parameter_colnames = param_names,x_names=x_names,
                     degree=1)
print_table(lm_cross)

```

# Random Forest



```{r rf}
rf_cross<-
  cross_validate_rf(total_data,ngroup=5,
                    parameter_colnames = param_names,x_names=x_names)
print_table(rf_cross)

```