---
title: "Traits"
author: "Ernesto Carrella"
date: "February 16, 2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning= FALSE, message=FALSE,
                      cache=TRUE,
                      dpi = 300, fig.width = 13.3, fig.height = 10)
library(abctools)
source('./setup.R')
library(tidyverse)
```

```{r dataprep}
library(EasyABC)
RUNS_TO_MAKE<-SMALL_DATA_SET_SIZE

run_trait_model<-function(I,h,A,sigma){
  simulation<-
    trait_model(c(500,
                  I,
                  h,
                  A,
                  1,
                  sigma
    ))
   return(
    data.frame(
      S=simulation[1],
      shannon_index=simulation[2],
      mean=simulation[3],
      skew=simulation[4]
    )
    
  )
}

total_data<-
  data.frame(
    I = runif(RUNS_TO_MAKE,3,5),
    h= runif(RUNS_TO_MAKE,-25,125),
    A= runif(RUNS_TO_MAKE,0.1,5),
    sigma = runif(RUNS_TO_MAKE,0.5,25)

  )
total_data<-pmap_df(total_data,run_trait_model) %>% cbind(total_data)


param_names<-c("I","h","A","sigma")
x_names<-setdiff(colnames(total_data),param_names)

```

# ABC

## Rejection


```{r rejection}
rejection_cross<-
  cross_validate_abc(total_data,ngroup=5,method="rejection",parameter_colnames = param_names)
print_table(rejection_cross)

```

## Rejection - semiauto


```{r rejection-sabc}
rejection_cross_sabc<-
  cross_validate_abc(total_data,ngroup=5,method="rejection",parameter_colnames = param_names,
                     semiauto = TRUE)
print_table(rejection_cross_sabc)

```

## Rejection - 1D


```{r rejection-sabc1d}
rejection_cross_sabc1d<-
  cross_validate_abc(total_data,ngroup=5,method="rejection",parameter_colnames = param_names,
                     semiauto = TRUE,
                     satr=list(function(x){outer(x,Y=1,"^")}))
print_table(rejection_cross_sabc1d)

```

## Loclin


```{r loclin}
loclin_cross<-
  cross_validate_abc(total_data,ngroup=5,method="loclinear",
                     hcorr=TRUE,parameter_colnames = param_names,
                     semiauto = FALSE)
print_table(loclin_cross)

```

## Loclin - semiauto


```{r loclin-sabc}
loclin_cross_sabc<-
  cross_validate_abc(total_data,ngroup=5,method="loclinear",
                     hcorr=TRUE,parameter_colnames = param_names,
                     semiauto = TRUE)
print_table(loclin_cross_sabc)

```

## Loclin - 1D


```{r loclin-sabc1d}
loclin_cross_sabc1d<-
  cross_validate_abc(total_data,ngroup=5,method="loclinear",
                     hcorr=TRUE,parameter_colnames = param_names,
                     semiauto = TRUE,
                     satr=list(function(x){outer(x,Y=1,"^")}))
print_table(loclin_cross_sabc1d)

```

## Neural-Network

```{r neuralnet, eval=FALSE, message= FALSE}
neuralnet<-
  cross_validate_abc(total_data,ngroup=5,method="neuralnet",
                     hcorr=TRUE,parameter_colnames = param_names)
print_table(neuralnet)

```

# Linear regression


## Degree 1

```{r lm}
lm_cross<-
  cross_validate_lm(total_data,ngroup=5,
                    parameter_colnames = param_names,x_names=x_names,
                     degree=1)
print_table(lm_cross)

```

